### ISSUE TITLE
Save into a google drive mapped on gnome

### ISSUE THREAD

**Issue by pablodav** [flathub/org.libreoffice.LibreOffice#23] opened 2018-03-21 02:06 UTC
OS: Fedora 27
Flatpak version: 0.10.3

When I open libreoffice writer and try to save into a google-drive connected with gnome-onlin-accounts, it fails with message 'File doesn't exists'.

It works with local install from fedora repos.

Flatpak output in terminal:

```shell
flatpak run org.libreoffice.LibreOffice 

(soffice:14): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.

(soffice:14): GLib-CRITICAL **: g_file_test: assertion 'filename != NULL' failed
```

![imagen](https://user-images.githubusercontent.com/4460447/37691795-1b38f224-2c93-11e8-80f2-738bbfcf0e5e.png)

![imagen](https://user-images.githubusercontent.com/4460447/37691801-26691a52-2c93-11e8-9dc3-4a1a606242f8.png)

Is it something to fix on flatpak / flatpak package? Something that will be fixed on next gnome version?

**Comment by stbergmann** [comment] 2018-03-27 08:49
What happens is that LO (in Content::transfer, ucb/source/ucp/gio/gio_content.cxx) calls GIO (from the underlying GNOME runtime) g_file_move to move local temporary <file:///tmp/XXXXXX.tmp/YYYYYY.tmp> to <google-drive://.../Sin título 1>.  The local /tmp file is relative to LO's sandbox'ed file system, but whatever the code that is ultimately triggered by GIO's g_file_move, it apparently wants to access it from outside the sandbox, causing the g_file_move to fail with "No such file or directory".

@alexlarsson, any thoughts?

**Comment by nedrichards** [comment] 2018-03-27 12:19
Seems like something to report to https://github.com/flatpak/xdg-desktop-portal/

**Comment by pablodav** [comment] 2018-05-18 02:16
Hi all,
I haven't tried with libreoffice again, but today working with another flatpak app: 'openshot' when I tried to save a file in $HOME/Vídeos  it failed due to some error with special characters.

I had to reinstall my system due to some other things, so I haven´t libreoffice with flatpak ready to test.

**Comment by pablodav** [comment] 2018-09-24 02:35
I haven't tried again, as this error stopped me in the usage of libreoffice in flatpak, will close the issue as similar one is closed #84

In the future will try again with flatpak version of libreoffice and if the error happens, will report again.

**Comment by stbergmann** [comment] 2021-06-08 15:08
lets keep this issue open (see analysis in comment at <https://github.com/flathub/org.libreoffice.LibreOffice/issues/23#issuecomment-376446424>)

**Comment by ondrejholy** [comment] 2021-06-18 11:03
I see more problems here:
- The ` g_file_test: assertion 'filename != NULL' failed` critical is printed when "Save as" is used and came from `SalGtkFilePicker::execute()`. `gFileName` is for some reason `NULL`. I'm not entirely sure why, I have some issues with `gdb` under Flatpak. But I guess this is because `g_file_get_uri` is used to get URIs, so it looks like e.g. `google-drive://user@gmail.com/path/file`, but later the code uses `g_filename_from_uri` which doesn't work for other schemes than `file:` (see https://gitlab.gnome.org/GNOME/glib/-/blame/main/glib/gconvert.c#L1685). The `g_file_query_exists` function should be used instead of `g_file_test` here. This seems to be unrelated to the Flatpaked version though.
- Another problem is the actual "Save" operation, where `g_file_move`/`g_file_copy` fails with `Nonexistent file`. This is not a problem on the LibreOffice side, but it should be possible to temporarily fix this if you change the file location to some which is accessible from the host, or by `--filesystem=/tmp`. The problem here is that the gvfs daemons are running on the host and tries to access the host's `/tmp` files. We have to do something with it...
- But it seems that with recent gvfs versions, it is not even possible to open remote files. This can be fixed by `--filesystem=xdg-run/gvfsd`. 

So "Open" and "Save" works nicely with `--filesystem=xdg-run/gvfsd` and `--filesystem=/tmp` on Fedora 34 Silverblue, the "Save as" works as well, just the check for already existing files fails, but this needs to be fixed in LibreOffice codebase...

**Comment by CharoSW** [comment] 2021-11-08 10:06
Has anyone done more digging with this?  I've had those options in since I saw the comment and they seem to work fine with the only draw back seeming to be that Libreoffice tries to mount my Google Drive a whole bunch of times if i open it before mounting the drive myself.  That does create a whole bunch of entries in Nautilus which aren't wanted but I also have no knowledge of how to fix/stop that issue

**Comment by luca-demma** [comment] 2022-05-05 11:22
The issue is present currently with the latest flatpak version 🙁

**Comment by KairanD** [comment] 2022-11-25 09:19
This is happening here on Manjaro GNOME (fresh install from yesterday). Packages gvfs, gvfs-google and gvs-goa are installed.

This was not happening on Manjaro KDE with the package kio-gdrive installed.

**Comment by stbergmann** [comment] 2023-02-21 12:55
>     * The ` g_file_test: assertion 'filename != NULL' failed` critical is printed when "Save as" is used and came from `SalGtkFilePicker::execute()`. `gFileName` is for some reason `NULL`. I'm not entirely sure why, I have some issues with `gdb` under Flatpak. But I guess this is because `g_file_get_uri` is used to get URIs, so it looks like e.g. `google-drive://user@gmail.com/path/file`, but later the code uses `g_filename_from_uri` which doesn't work for other schemes than `file:` (see https://gitlab.gnome.org/GNOME/glib/-/blame/main/glib/gconvert.c#L1685). The `g_file_query_exists` function should be used instead of `g_file_test` here. This seems to be unrelated to the Flatpaked version though.

It looks like the relevant `g_file_test` call has meanwhile gone from `SalGtkFilePicker::execute` with <https://git.libreoffice.org/core/+/67a3ea1852a73a25980250473b0fd43a8392f779%5E!/> "Related: [tdf#145169](https://bugs.documentfoundation.org/show_bug.cgi?id=145169) warn on overwrite from gtk "save as" for remote files".  And I don't see any "GLib-CRITICAL **: g_file_test: assertion 'filename != NULL' failed" output when I try to Save or Save As a remote document with the latest LO 7.5.0 flatpak. 

>     * Another problem is the actual "Save" operation, where `g_file_move`/`g_file_copy` fails with `Nonexistent file`. This is not a problem on the LibreOffice side, but it should be possible to temporarily fix this if you change the file location to some which is accessible from the host, or by `--filesystem=/tmp`. The problem here is that the gvfs daemons are running on the host and tries to access the host's `/tmp` files. We have to do something with it...

@ondrejholy Has there been any progress here?  Shall I file an issue somewhere?

>     * But it seems that with recent gvfs versions, it is not even possible to open remote files. This can be fixed by `--filesystem=xdg-run/gvfsd`.

This has meanwhile been fixed with <https://github.com/flathub/org.libreoffice.LibreOffice/commit/4226084c374eac66c520837a81c517a98541543d> "Adding xdg-run/gvfsd".

**Closed** 2023-02-28 11:17 UTC
