### ISSUE TITLE
Doesn't open files in network shares

### ISSUE THREAD

**Issue by TiZ-EX1** [flathub/org.libreoffice.LibreOffice#3] opened 2017-11-27 15:52 UTC
Hi there. For some reason, I can't open files in mounted SMB shares using the flatpak version of LibreOffice. When I open a network share file from Thunar, the splash screen appears and then after it fully loads, no main window appears. When I open the application and then try to go to the network share from the file chooser, I get an error dialog saying "Operation not supported."

This is necessary for my job; without this I can't use the flatpak version of LibreOffice in a production employment setting.

**Comment by stbergmann** [comment] 2017-11-28 14:10
That's caused by a missing --talk-name=org.gtk.vfs.* after --socket=session-bus had been removed.  I'll provide fresh builds.  Until then, you should be able to temporarily fix it locally with something like

  flatpak override --talk-name=org.gtk.vfs.\* org.libreoffice.LibreOffice

in a terminal.

**Comment by TiZ-EX1** [comment] 2017-11-28 16:06
That override works; thank you!

**Comment by stbergmann** [comment] 2017-11-29 17:00
seen fixed in flatpak rev 45ef1097dcad

**Closed by stbergmann** 2017-11-29 17:00 UTC
