### ISSUE TITLE
Cannot save to network drive

### ISSUE THREAD

**Issue by yajo** [flathub/org.libreoffice.LibreOffice#135] opened 2020-10-31 14:01 UTC
In GNOME, I enabled a nextcloud drive. If I double-click one document in it, it opens with LO fine, but if I try to save, it fails. I have to save it to some local folder and then copy it later to the nextcloud drive.

**Comment by stbergmann** [comment] 2020-11-02 07:46
Do you know whether that only happens with the flatpak version of LibreOffice, or also with other versions (like a distro-provided one, or one downloaded from <https://www.libreoffice.org/download/download/>)?

**Comment by Yajo** [comment] 2020-11-03 17:15
I had this similar issue years ago, could it be related? It got fixed in Fedora quickly: https://bugzilla.redhat.com/show_bug.cgi?id=1134285

**Comment by stbergmann** [comment] 2021-06-08 15:05
This is probably the same as <https://github.com/flathub/org.libreoffice.LibreOffice/issues/23> "Save into a google drive mapped on gnome".

**Comment by Yajo** [comment] 2021-06-08 16:24
Yes, seems to be the same.

**Comment by ondrejholy** [comment] 2021-06-18 11:01
> I had this similar issue years ago, could it be related? It got fixed in Fedora quickly: https://bugzilla.redhat.com/show_bug.cgi?id=1134285

This seems to be totally unrelated.

> Yes, seems to be the same.

In general, Google Drive implementation is kinda specific and might require more fixes in comparison to NextCloud and others, but in this case, I think that it can be closed as a duplicate of #23.

**Comment by KyleRConway** [comment] 2023-02-05 19:14
I'm running Fedora Silverblue, so also running the LO flatpak, and opening a nextcloud document works fine, but trying to save produces this dialogue message in LibreOffice:

"Error saving the document [document name]: Nonexistent file"

I'm using the built-in Gnome "Online Accounts" integration for nextcloud connection.

**Closed** 2023-02-21 13:00 UTC
