### ISSUE TITLE
KDE open/save dialogs?

### ISSUE THREAD

**Issue by DougBeney** [flathub/org.libreoffice.LibreOffice#112] opened 2020-02-03 15:06 UTC
I'm curious if it will be possible to get KDE file dialogs for Flatpak Libreoffice.

The regular Libreoffice does this through xdg-desktop-portal I believe.

**Comment by Erick555** [comment] 2020-02-07 19:18
AFAIK lo doesn't use xdg-desktop-portal filechooser backend on any platform. Lack of kde integration is caused by lack of [vcl plugin](https://github.com/flathub/org.libreoffice.LibreOffice/issues/63) and no qt/kde available in runtime

**Comment by Maltimore** [comment] 2020-04-18 11:43
In fact, could this issue be seen as a duplicate of the issue that @Erick555 linked? Then I think it should be closed in favor of that one.

**Comment by stbergmann** [comment] 2020-04-20 07:44
Yes, same as <https://github.com/flathub/org.libreoffice.LibreOffice/issues/63> "Flatpak LibreOffice 6.1.* vcl stuck with GTK on KDE Plasma and won't work with Global Menu".

**Closed by stbergmann** 2020-04-20 07:44 UTC
