### ISSUE TITLE
Cursor is tiny on HiDPI display

### ISSUE THREAD

**Issue by DougBeney** [flathub/org.libreoffice.LibreOffice#32] opened 2018-04-30 14:17 UTC
Hello,
I am on Fedora 27 and just installed the FlatHub LibreOffice.

I think it is very similar to [this issue from the past](https://github.com/flatpak/flatpak/issues/740). Please note, that particular issue talks about Spotify. The maintainers of the Spotify Flatpak have since fixed their tiny cursor problem.

[Here is a GIF showing the issue](https://i.imgur.com/g8HNfEU.gif)

I do not know that much about Flatpaks to clearly point out the issue, but I would imagine a good way to troubleshoot this would be to take a look at Spotify on Flathub as they have solved this issue.

**Comment by stbergmann** [comment] 2018-05-02 05:56
@ramcq, seems to be fallout from the GNOME to freedesktop.org runtime change.  I can reproduce this too, and when I roll back to before <https://github.com/flathub/org.libreoffice.LibreOffice/commit/7a2393f5fcab8c6938180c4718f2c61acd495528> "port to freedesktop.org 1.6 runtime" everything is fine again.

**Comment by ramcq** [comment] 2018-05-02 10:02
Wayland or X? Could be something to do with the gsettings we looked at before? I guess it's the same root cause as the icon theme thing. @alexlarsson any ideas?

**Comment by stbergmann** [comment] 2018-05-02 10:49
I can reproduce it on Wayland at least (didn't try X11).

**Comment by DougBeney** [comment] 2018-05-02 20:17
I am on Wayland as well.

**Comment by severin-lemaignan** [comment] 2018-05-02 22:50
Same issue here on wayland, with Gnome Calendar 3.28.2.
```
runtime=org.gnome.Platform/x86_64/3.28
```

**Comment by fkrull** [comment] 2018-05-03 17:08
Can reproduce as well (with Wayland). Setting the `XCURSOR_PATH` environment variable inside the sandbox before running the program gives me the correct cursors:

```
$ export XCURSOR_PATH=/run/host/share/icons/
$ /usr/lib/libreoffice/program/soffice
```

I feel like this should be handled by the runtime in some fashion, but if/while it isn't, this seems like a reasonable workaround.

**Comment by ramcq** [comment] 2018-05-15 09:46
@mclasen checked this out (I don't have a Walyand host) and found that the wayland cursor library hardcodes its own search path, and doesn't respect XDG_DATA_DIRS https://cgit.freedesktop.org/wayland/wayland/tree/cursor/xcursor.c#n620

It's not visible in the GNOME runtime because the Adwaita cursor theme is present in /usr/share/themes, but in the freedesktop runtime, it's in /usr/share/runtime/share/themes as it comes from the Adwaita theme extension.

I think @jadahl is taking a look now, should be a relatively easy patch we can pick into the fd.o runtime.

**Comment by stbergmann** [comment] 2018-06-07 09:06
seen fixed with recent org.freedesktop.Platform//1.6

**Closed by stbergmann** 2018-06-07 09:06 UTC

**Comment by mclasen** [comment] 2018-06-07 15:42
wrong mclasen



+-------------------------------+
Michael Clasen
mclasen@mclasen.com
925.285.5224
+-------------------------------+

**Comment by stbergmann** [comment] 2018-06-07 16:27
mclasen, can you elaborate what you mean with that "wrong mclasen"?

**Comment by nedrichards** [comment] 2018-06-07 21:00
@stbergmann you mean @matthiasclasen

**Comment by mclasen** [comment] 2018-06-07 22:34
bingo

**Comment by stbergmann** [comment] 2018-06-08 06:57
ah, @ramcq meant @matthiasclasen in his May 15 comment

(from that "wrong mclasen" comment I was slightly worried that mclasen claims that my comment was wrong that this issue is actually fixed)
