### ISSUE TITLE
bwrap: Can't mkdir parents for /run/host/usr: Permission denied

### ISSUE THREAD

**Issue by trialism** [flathub/org.libreoffice.LibreOffice#8] opened 2018-01-28 18:37 UTC
When I start libreoffice as `flatpak run org.libreoffice.LibreOffice` it throws the error to me what's in the title.

**Comment by stbergmann** [comment] 2018-01-29 08:52
So this doesn't appear to be an issue with the LO flatpak, but rather with flatpak and/or bwrap itself.  Closed as duplicate of <https://github.com/flatpak/flatpak/issues/1357>.

**Closed by stbergmann** 2018-01-29 08:52 UTC
