### ISSUE TITLE
Own theme selection doesn't work

### ISSUE THREAD

**Issue by evfool** [flathub/org.libreoffice.LibreOffice#47] opened 2018-06-19 06:30 UTC
Under preferences ->LibreOffice->Personalization, Own themes, Select theme dialog doesn't load any of the themes, setting a URL in the firefox theme url box freezes Libreoffice, clicking a Category also.
The only thing I can do in that dialog without freezing LibreOffice is click Cancel without/before clicking anything else.

Running 6.0.4.2 from flatpak
Build ID: 9b0d9b32d5dcda91d2f1a96dc04c645c450872bf
CPU threads: 4; OS: Linux 4.16; UI render: default; VCL: gtk3; 
Flatpak version
Locale: en-US (en_US.UTF-8); Calc: group

**Comment by stbergmann** [comment] 2018-06-19 07:34
This is a duplicate of upstream <https://bugs.documentfoundation.org/show_bug.cgi?id=117866> 'LibreOffice hangs if "Select Firefox Theme' dialog is dismissed before theme previews are completely loaded", which will be fixed in LO 6.1.

But note that this personalization doesn't work anyway in GTK3-based LO, and thus not in the LO Flatpak version either (which is always running as GTK3-based), see comment at <https://github.com/flathub/org.libreoffice.LibreOffice/issues/34#issuecomment-395355647> "Doesn't let me switch to 'pre installed' theme".

**Closed by stbergmann** 2018-06-19 07:34 UTC
