### ISSUE TITLE
strange behavier in Impress with a loaded video

### ISSUE THREAD

**Issue by Lvaskz** [flathub/org.libreoffice.LibreOffice#21] opened 2018-03-10 07:47 UTC
When upload a video in the slide shot  and I move a vertical bar, the background app has a strange behavior. I made a video.
[Impress LO.mp4.zip](https://github.com/flathub/org.libreoffice.LibreOffice/files/1799174/Impress.LO.mp4.zip)
 The video has a flicker.

**Comment by stbergmann** [comment] 2018-03-12 08:32
* What kind of desktop is that (GNOME, KDE, ...)?
* Which version of LO flatpak is that (see "Help - About LibreOffice")?
* Does it only happen if the LO Impress window is maximized?
* Recent versions of LO flatpak have --device=dri enabled. Does it also happen if you run LO with that disabled, `flatpak run --nodevice=dri org.libreoffice.LibreOffice` in a terminal?
* Does it also happen with a non-flatpak LO version?

**Comment by Lvaskz** [comment] 2018-03-12 16:53
- What  kind of desktop is that (GNOME, KDE, ...)? Linuxmint 18.3, 64 bit, desktop Cinnamon 3.6

- Which  version of LO flatpak is that (see "Help - About LibreOffice")? libreoffice 6.0.2

- Does it also happen with a non-flatpak LO version? Well, I have  appimage libreoffice 6.0.2 
 and I have not that issue. 

- Does it only happen if the LO Impress window is maximized? Well, at the moment yes, but i not tried with the window minimized, I will try to night.

- Recent versions of LO flatpak have --device=dri enabled. Does it also happen if you run LO with that disabled, flatpak run --nodevice=dri org.libreoffice.LibreOffice in a terminal? I will try to night

**Comment by Lvaskz** [comment] 2018-03-13 20:12
**- Does it only happen if the LO Impress window is maximized?** minimized or maximized windows has the same problem.

**Comment by Lvaskz** [comment] 2018-03-13 20:13
**- Recent versions of LO flatpak have --device=dri enabled. Does it also happen if you run LO with that disabled, flatpak run --nodevice=dri org.libreoffice.LibreOffice in a terminal?**Same problem

**Comment by stbergmann** [comment] 2018-03-14 08:25
I assume this is a problem in the underlying software stack that the LO flatpak can do little about.  The LO flatpak, using the org.gnome.Platform flatpak runtime, always uses LO's GTK3 backend; your system's or an appimage LO may use a different backend, which might be one reason why you only experience the issue with the flatpak LO.
Just in case: does this happen to sound familiar for LO's vclplug_gtk3, @caolanm, or for org.gnome.Platform in general, @alexlarsson?

**Comment by caolanm** [comment] 2018-03-14 08:53
Possibly this is known as https://bugs.documentfoundation.org/show_bug.cgi?id=111850 or something similar, is there a /usr/lib*/gstreamer-1.0/libgstgtksink.so in the underlying runtime ?

**Comment by stbergmann** [comment] 2018-03-14 09:10
"is there a /usr/lib*/gstreamer-1.0/libgstgtksink.so in the underlying runtime ?"  no:

> $ flatpak run --command=bash org.libreoffice.LibreOffice -c 'ls /usr/lib/gstreamer-1.0/libgst*sink.so'
> /usr/lib/gstreamer-1.0/libgstfbdevsink.so
> /usr/lib/gstreamer-1.0/libgstwaylandsink.so
> /usr/lib/gstreamer-1.0/libgstximagesink.so
> /usr/lib/gstreamer-1.0/libgstxvimagesink.so

**Comment by caolanm** [comment] 2018-03-14 09:42
So I assume that means that in avmedia/source/gstreamer/gstplayer.cxx the pVideosink from gst_element_factory_make("gtksink"... is null and the fallback is used.

FWIW in fedora gstreamer1-plugins-bad-free-gtk contains the /usr/lib64/gstreamer-1.0/libgstgtk.so (seems I had the wrong name above anyway) which is the (wayland-aware) backend we default to.

That said, dunno if using that backend would actually solve this or not

**Comment by stbergmann** [comment] 2018-03-14 10:04
"FWIW in fedora gstreamer1-plugins-bad-free-gtk contains the /usr/lib64/gstreamer-1.0/libgstgtk.so (seems I had the wrong name above anyway) which is the (wayland-aware) backend we default to."

That one is available in the flatpak alright:
> $ flatpak run --command=bash org.libreoffice.LibreOffice -c 'ls /usr/lib/gstreamer-1.0/libgstgtk.so'
> /usr/lib/gstreamer-1.0/libgstgtk.so

**Comment by caolanm** [comment] 2018-03-14 10:28
Yeah, so that's as good as it gets then and the remaining issues are the same as the upstream bug.

**Comment by stbergmann** [comment] 2018-03-14 11:02
So closing as a duplicate of upstream <https://bugs.documentfoundation.org/show_bug.cgi?id=111850> "UI breaks after scrolling somewhere while playing video".

**Closed by stbergmann** 2018-03-14 11:02 UTC
