### ISSUE TITLE
Separate the applications

### ISSUE THREAD

**Issue by arteeh** [flathub/org.libreoffice.LibreOffice#147] opened 2021-04-14 10:03 UTC
In my opinion, a flatpak shouldn't contain more than one app. I would like to have Writer, Impress, Calc, et cetera as their own flatpaks so that I can choose to only install what I actually use. Common elements (from which I understand Libreoffice has a lot, and is I assume the reason why they're bundled) could be put in a 'Base' flatpak (e.g. org.libreoffice.Common) to minimize duplication.

**Comment by Erick555** [comment] 2021-04-14 10:34
That would complicate the maintenance greatly as one need to handle multiple github repos at once.

**Comment by stbergmann** [comment] 2021-04-14 10:51
By design, LibreOffice is really just one app, even if in some places (e.g., XDG .desktop files) it tries to pretend it is not.
And while it typically kind-of works to allow partial LibreOffice installations (e.g., the Windows installer, or your typical Linux distro), that's more by accident than by fundamental design, and if you run into an issue with such a partial installation, the fix is to make it less partial by installing more of the "optional" components.  But with LibreOffice split into multiple flatpaks, that sort of fix would not work.
So, closing this as wontfix.

**Closed by stbergmann** 2021-04-14 10:51 UTC

**Comment by mcatanzaro** [comment] 2025-11-04 14:21
I do pretty strongly agree that a Flatpak should contain only one user-visible application. Otherwise, installing one application will appear to also install the other applications without the user's permission. If I were a Flathub reviewer (which I am not), then I would have blocked LibreOffice until it was split up one way or another. But under the hood, all of LibreOffice is really just one binary, so the goal would be to provide the _illusion_ of app independence.

Having a LibreOffice runtime is actually a pretty reasonable proposal, and probably the best way to do this. This would create the illusion of having separate LibreOffice applications so the user can install just one at a time, like Fedora does. Basically everything that is currently built in the flatpak-builder manifest would need to go into the runtime. Then the apps themselves would contain only the desktop file and appstream metainfo for one of the LibreOffice applications.

Alternative: just have a bunch of different copies of the existing LibreOffice app, each of which deletes all but one of the other desktop files and appstream metainfos.

**Comment by AdrianVovk** [comment] 2025-11-04 15:44
We have BaseApps for this kind of shared resource between a couple different apps

But also the different libreoffice "sub-apps" are actually all the same app. Like, more than just "oh they're all compiled into one multicall binary". They're literally the same app, even at runtime. I can start in LibreOffice Writer, then click File > Close and that very same window transforms into the "LibreOffice" app. I can then click on "Calc Spreadsheet" and end up in an instance of LibreOffice Calc, still within the same window.

So if anything, LibreOffice could combine its various .desktop files into just one "LibreOffice" app, rather than having distinct "LibreOffice Writer"/"LibreOffice Calc"/etc "apps". That would be most representative of the reality of how LibreOffice works
